-- ==============================================================================
-- Gaming Solutions: Bitácora de Auditoría y Triggers Centralizados
-- ==============================================================================

-- 1. TABLA CENTRALIZADA DE AUDITORÍA
DECLARE
  l_cantidad_tablas NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_cantidad_tablas
    FROM USER_TABLES
   WHERE TABLE_NAME = 'BITACORA_AUDITORIA';

  IF l_cantidad_tablas = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE BITACORA_AUDITORIA (
        ID_AUDITORIA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
        TABLA_AFECTADA VARCHAR2(50) NOT NULL,
        ID_REGISTRO NUMBER,
        OPERACION CHAR(1) NOT NULL,
        USUARIO_BD VARCHAR2(128) DEFAULT USER NOT NULL,
        FECHA_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        VALORES_ANTERIORES CLOB,
        VALORES_NUEVOS CLOB,
        CONSTRAINT PK_BITACORA_AUDITORIA PRIMARY KEY (ID_AUDITORIA),
        CONSTRAINT CK_BITACORA_OPERACION CHECK (OPERACION IN (''I'',''U'',''D''))
      )';
  END IF;
END;
/

-- 2. TRIGGER DE AUDITORÍA PARA PRODUCTOS
CREATE OR REPLACE TRIGGER TRG_AUD_PRODUCTOS
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTOS
FOR EACH ROW
DECLARE
  l_id_registro NUMBER;
  l_valores_anteriores CLOB;
  l_valores_nuevos CLOB;
  l_nombre VARCHAR2(150);
  l_stock NUMBER;
  l_precio_venta NUMBER;
  l_activo CHAR(1);
  l_operacion CHAR(1);
BEGIN
  IF INSERTING THEN
    l_operacion := 'I';
  ELSIF UPDATING THEN
    l_operacion := 'U';
  ELSE
    l_operacion := 'D';
  END IF;

  IF INSERTING OR UPDATING THEN
    l_id_registro := :NEW.ID_PRODUCTO;
    l_nombre := :NEW.NOMBRE;
    l_stock := :NEW.STOCK;
    l_precio_venta := :NEW.PRECIO_VENTA;
    l_activo := :NEW.ACTIVO;
    l_valores_nuevos := TO_CLOB(
      '{"NOMBRE":"' || REPLACE(l_nombre, '"', '\"') ||
      '","STOCK":' || l_stock ||
      ',"PRECIO_VENTA":' || l_precio_venta ||
      ',"ACTIVO":"' || l_activo || '"}'
    );
  ELSE
    l_id_registro := :OLD.ID_PRODUCTO;
  END IF;

  IF UPDATING OR DELETING THEN
    l_nombre := :OLD.NOMBRE;
    l_stock := :OLD.STOCK;
    l_precio_venta := :OLD.PRECIO_VENTA;
    l_activo := :OLD.ACTIVO;
    l_valores_anteriores := TO_CLOB(
      '{"NOMBRE":"' || REPLACE(l_nombre, '"', '\"') ||
      '","STOCK":' || l_stock ||
      ',"PRECIO_VENTA":' || l_precio_venta ||
      ',"ACTIVO":"' || l_activo || '"}'
    );
  END IF;

  INSERT INTO BITACORA_AUDITORIA (
    TABLA_AFECTADA, ID_REGISTRO, OPERACION, VALORES_ANTERIORES, VALORES_NUEVOS
  )
  VALUES (
    'PRODUCTOS',
    l_id_registro,
    l_operacion,
    l_valores_anteriores,
    l_valores_nuevos
  );
END;
/

-- 3. TRIGGER DE AUDITORÍA PARA CERTIFICADOS DE INSPECCIÓN GS
CREATE OR REPLACE TRIGGER TRG_AUD_CERTIFICADOS_GS
AFTER INSERT OR UPDATE OR DELETE ON CERTIFICADOS_GS
FOR EACH ROW
DECLARE
  l_id_registro NUMBER;
  l_valores_anteriores CLOB;
  l_valores_nuevos CLOB;
  l_codigo VARCHAR2(30);
  l_hw_pct NUMBER;
  l_estetico_pct NUMBER;
  l_termico_pct NUMBER;
  l_operacion CHAR(1);
BEGIN
  IF INSERTING THEN
    l_operacion := 'I';
  ELSIF UPDATING THEN
    l_operacion := 'U';
  ELSE
    l_operacion := 'D';
  END IF;

  IF INSERTING OR UPDATING THEN
    l_id_registro := :NEW.ID_CERTIFICADO;
    l_codigo := :NEW.CODIGO_CERTIFICADO;
    l_hw_pct := :NEW.HARDWARE_ORIGINAL_PCT;
    l_estetico_pct := :NEW.ESTADO_ESTETICO_PCT;
    l_termico_pct := :NEW.RENDIMIENTO_TERMICO_PCT;
    l_valores_nuevos := TO_CLOB(
      '{"CODIGO":"' || REPLACE(l_codigo, '"', '\"') ||
      '","HW_PCT":' || l_hw_pct ||
      ',"ESTETICO_PCT":' || l_estetico_pct ||
      ',"TERMICO_PCT":' || l_termico_pct || '}'
    );
  ELSE
    l_id_registro := :OLD.ID_CERTIFICADO;
  END IF;

  IF UPDATING OR DELETING THEN
    l_codigo := :OLD.CODIGO_CERTIFICADO;
    l_hw_pct := :OLD.HARDWARE_ORIGINAL_PCT;
    l_estetico_pct := :OLD.ESTADO_ESTETICO_PCT;
    l_termico_pct := :OLD.RENDIMIENTO_TERMICO_PCT;
    l_valores_anteriores := TO_CLOB(
      '{"CODIGO":"' || REPLACE(l_codigo, '"', '\"') ||
      '","HW_PCT":' || l_hw_pct ||
      ',"ESTETICO_PCT":' || l_estetico_pct ||
      ',"TERMICO_PCT":' || l_termico_pct || '}'
    );
  END IF;

  INSERT INTO BITACORA_AUDITORIA (
    TABLA_AFECTADA, ID_REGISTRO, OPERACION, VALORES_ANTERIORES, VALORES_NUEVOS
  )
  VALUES (
    'CERTIFICADOS_GS',
    l_id_registro,
    l_operacion,
    l_valores_anteriores,
    l_valores_nuevos
  );
END;
/

-- 4. TRIGGER DE AUDITORÍA PARA VENTAS
CREATE OR REPLACE TRIGGER TRG_AUD_VENTAS
AFTER INSERT OR UPDATE OR DELETE ON VENTAS
FOR EACH ROW
DECLARE
  l_id_registro NUMBER;
  l_valores_anteriores CLOB;
  l_valores_nuevos CLOB;
  l_id_cliente NUMBER;
  l_total_venta NUMBER;
  l_estado_venta VARCHAR2(20);
  l_metodo_pago VARCHAR2(20);
  l_operacion CHAR(1);
BEGIN
  IF INSERTING THEN
    l_operacion := 'I';
  ELSIF UPDATING THEN
    l_operacion := 'U';
  ELSE
    l_operacion := 'D';
  END IF;

  IF INSERTING OR UPDATING THEN
    l_id_registro := :NEW.ID_VENTA;
    l_id_cliente := :NEW.ID_CLIENTE;
    l_total_venta := :NEW.TOTAL_VENTA;
    l_estado_venta := :NEW.ESTADO_VENTA;
    l_metodo_pago := :NEW.METODO_PAGO;
    l_valores_nuevos := TO_CLOB(
      '{"ID_CLIENTE":' || l_id_cliente ||
      ',"TOTAL_VENTA":' || l_total_venta ||
      ',"ESTADO_VENTA":"' || l_estado_venta ||
      '","METODO_PAGO":"' || l_metodo_pago || '"}'
    );
  ELSE
    l_id_registro := :OLD.ID_VENTA;
  END IF;

  IF UPDATING OR DELETING THEN
    l_id_cliente := :OLD.ID_CLIENTE;
    l_total_venta := :OLD.TOTAL_VENTA;
    l_estado_venta := :OLD.ESTADO_VENTA;
    l_metodo_pago := :OLD.METODO_PAGO;
    l_valores_anteriores := TO_CLOB(
      '{"ID_CLIENTE":' || l_id_cliente ||
      ',"TOTAL_VENTA":' || l_total_venta ||
      ',"ESTADO_VENTA":"' || l_estado_venta ||
      '","METODO_PAGO":"' || l_metodo_pago || '"}'
    );
  END IF;

  INSERT INTO BITACORA_AUDITORIA (
    TABLA_AFECTADA, ID_REGISTRO, OPERACION, VALORES_ANTERIORES, VALORES_NUEVOS
  )
  VALUES (
    'VENTAS',
    l_id_registro,
    l_operacion,
    l_valores_anteriores,
    l_valores_nuevos
  );
END;
/
