-- ==============================================================================
-- Gaming Solutions: Seed Data (Datos de Prueba Reales con Certificados #GS)
-- Ejecutar después de 01_schema.sql y 02_auditoria.sql
-- ==============================================================================

-- 1. INSERSIONES DE ROLES Y USUARIOS
INSERT INTO ROLES (NOMBRE_ROL, DESCRIPCION) VALUES ('Administrador General', 'Control total de inventario, ventas y usuarios');
INSERT INTO ROLES (NOMBRE_ROL, DESCRIPCION) VALUES ('Técnico Certificador', 'Inspección de hardware y emisión de Certificados GS');
INSERT INTO ROLES (NOMBRE_ROL, DESCRIPCION) VALUES ('Vendedor / Cajero', 'Registro de ventas en efectivo y atención al cliente');

INSERT INTO USUARIOS (ID_ROL, USERNAME, EMAIL, NOMBRE_COMPLETO) 
VALUES (1, 'admin', 'admin@gamingsolutions.pe', 'Carlos Mendoza - Admin Master');

INSERT INTO USUARIOS (ID_ROL, USERNAME, EMAIL, NOMBRE_COMPLETO) 
VALUES (2, 'tecnico.lab', 'lab@gamingsolutions.pe', 'Ing. Roberto Silva - Lab Hardware');

-- 2. INSERSIONES DE CATEGORÍAS
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION, GARANTIA_MESES_DEFECTO, SLUG)
VALUES ('Consolas Next-Gen', 'Consolas selladas y de reventa verificada, probadas en laboratorio', 12, 'consolas-next-gen');

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION, GARANTIA_MESES_DEFECTO, SLUG)
VALUES ('Laptops Gamer', 'Equipos de alto rendimiento con pruebas de estrés térmico, GPU y batería', 18, 'laptops-gamer');

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION, GARANTIA_MESES_DEFECTO, SLUG)
VALUES ('Retro Restoration', 'Consolas retro recapacitadas con carcasas restauradas a mano', 6, 'retro-restoration');

-- 3. INSERSIONES DE PROVEEDORES
INSERT INTO PROVEEDORES (NOMBRE, TIPO_PROVEEDOR, TELEFONO, EMAIL, DIRECCION)
VALUES ('Distribuciones Next Level S.A.C.', 'EMPRESA', '+51 987 654 321', 'ventas@nextlevel.pe', 'Av. Argentina 1420, Lima');

INSERT INTO PROVEEDORES (NOMBRE, TIPO_PROVEEDOR, TELEFONO, EMAIL, DIRECCION)
VALUES ('Jorge Mendoza (Coleccionista Particular)', 'PARTICULAR', '+51 912 345 678', 'jorge.retro@gmail.com', 'Calle Los Olivos 450, Miraflores');

-- 4. INSERSIONES DE CLIENTES
INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL, DIRECCION)
VALUES ('María González', '+51 999 111 222', 'maria.gonzalez@gmail.com', 'Av. Javier Prado Este 2500, San Borja');

INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL, DIRECCION)
VALUES ('Carlos Ramírez', '+51 988 222 333', 'carlos.ramirez@outlook.com', 'Jr. Carabaya 540, Cercado de Lima');

INSERT INTO CLIENTES (NOMBRE, TELEFONO, EMAIL, DIRECCION)
VALUES ('Ana Torres', '+51 977 333 444', 'ana.torres@hotmail.com', 'Av. Benavides 1890, Surco');

-- 5. INSERSIONES DE PRODUCTOS (NEXT-GEN, LAPTOPS, RETRO)
-- ID_PRODUCTO 1: PS5 Slim (Next-Gen)
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_PROVEEDOR, SKU, NOMBRE, MARCA, MODELO, TIPO_HARDWARE, PRECIO_VENTA, PRECIO_COMPRA, STOCK, DESCRIPCION)
VALUES (1, 1, 'PS5-SLIM-01', 'PlayStation 5 Slim Digital Edition', 'Sony', 'CFI-2015', 'NEXT_GEN', 499.99, 420.00, 8, 'Consola PS5 Slim de 1TB SSD con sello de verificación en laboratorio y firmware actualizado.');

-- ID_PRODUCTO 2: Nintendo Switch OLED (Next-Gen)
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_PROVEEDOR, SKU, NOMBRE, MARCA, MODELO, TIPO_HARDWARE, PRECIO_VENTA, PRECIO_COMPRA, STOCK, DESCRIPCION)
VALUES (1, 1, 'NSW-OLED-WHT', 'Nintendo Switch OLED White Edition', 'Nintendo', 'HEG-001', 'NEXT_GEN', 349.99, 290.00, 5, 'Pantalla OLED de 7 pulgadas, 64GB de almacenamiento interno con dock Ethernet.');

-- ID_PRODUCTO 3: Xbox Series X (Next-Gen)
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_PROVEEDOR, SKU, NOMBRE, MARCA, MODELO, TIPO_HARDWARE, PRECIO_VENTA, PRECIO_COMPRA, STOCK, DESCRIPCION)
VALUES (1, 1, 'XSX-1TB-BLK', 'Xbox Series X 1TB Black', 'Microsoft', 'RRT-00010', 'NEXT_GEN', 479.99, 400.00, 3, '12 Teraflops de potencia de procesamiento gráfico, arquitectura Velocity de 1TB SSD.');

-- ID_PRODUCTO 4: Laptop ASUS ROG Strix (Laptop Gamer)
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_PROVEEDOR, SKU, NOMBRE, MARCA, MODELO, TIPO_HARDWARE, PRECIO_VENTA, PRECIO_COMPRA, STOCK, DESCRIPCION)
VALUES (2, 1, 'LAP-ROG-G16', 'ASUS ROG Strix G16 RTX 4070', 'ASUS', 'G614JI-N4003W', 'LAPTOP', 1499.99, 1250.00, 4, 'Laptop Gamer de alto rendimiento con Intel Core i7-13650HX, RTX 4070 8GB y pantalla 240Hz.');

-- ID_PRODUCTO 5: Laptop MSI Raider (Laptop Gamer)
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_PROVEEDOR, SKU, NOMBRE, MARCA, MODELO, TIPO_HARDWARE, PRECIO_VENTA, PRECIO_COMPRA, STOCK, DESCRIPCION)
VALUES (2, 1, 'LAP-MSI-GE78', 'MSI Raider GE78 HX i9 RTX 4080', 'MSI', 'GE78-HX-13VH', 'LAPTOP', 2199.99, 1850.00, 2, 'Potencia extrema con Intel i9-13980HX, NVIDIA RTX 4080 12GB y disipación Cooler Boost 5.');

-- ID_PRODUCTO 6: Super Nintendo SNES (Retro Restoration)
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_PROVEEDOR, SKU, NOMBRE, MARCA, MODELO, TIPO_HARDWARE, PRECIO_VENTA, PRECIO_COMPRA, STOCK, DESCRIPCION)
VALUES (3, 2, 'RET-SNES-1991', 'Super Nintendo SNES 100% Recapacitada', 'Nintendo', 'SNS-001', 'RETRO', 189.99, 100.00, 2, 'Consola SNES recapacitada con capacitores SMD japoneses, carcasa blanqueada por retrabado UV.');

-- ID_PRODUCTO 7: Game Boy Color (Retro Restoration)
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_PROVEEDOR, SKU, NOMBRE, MARCA, MODELO, TIPO_HARDWARE, PRECIO_VENTA, PRECIO_COMPRA, STOCK, DESCRIPCION)
VALUES (3, 2, 'RET-GBC-PURP', 'Game Boy Color Atomic Purple Restaurada', 'Nintendo', 'CGB-001', 'RETRO', 129.99, 60.00, 1, 'Recapacitado completo de audio, altavoz nuevo reemplazado y pantalla limpia sin rasguños.');

-- ID_PRODUCTO 8: Sega Genesis (Retro Restoration)
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_PROVEEDOR, SKU, NOMBRE, MARCA, MODELO, TIPO_HARDWARE, PRECIO_VENTA, PRECIO_COMPRA, STOCK, DESCRIPCION)
VALUES (3, 2, 'RET-GEN-MOD1', 'Sega Genesis Model 1 HD Graphics', 'Sega', 'MK-1601', 'RETRO', 159.99, 75.00, 4, 'Legendario Modelo 1 con salida de auriculares limpia, capacitores cambiados y mandos limpios.');

-- 6. INSERSIONES DE CERTIFICADOS GS (TRANSPARENCIA TOTAL)
INSERT INTO CERTIFICADOS_GS (ID_PRODUCTO, CODIGO_CERTIFICADO, HARDWARE_ORIGINAL_PCT, ESTADO_ESTETICO_PCT, RENDIMIENTO_TERMICO_PCT, PUNTOS_REVISADOS, MESES_GARANTIA, DETALLE_INSPECCION)
VALUES (1, '#GS-2201', 100, 96, 98, 35, 12, 'Pruebas térmicas bajo carga FurMark/3DMark aprobadas. Lectora de disco impecable. Garantía 12 meses.');

INSERT INTO CERTIFICADOS_GS (ID_PRODUCTO, CODIGO_CERTIFICADO, HARDWARE_ORIGINAL_PCT, ESTADO_ESTETICO_PCT, RENDIMIENTO_TERMICO_PCT, PUNTOS_REVISADOS, MESES_GARANTIA, DETALLE_INSPECCION)
VALUES (2, '#GS-2202', 100, 98, 97, 32, 12, 'Pantalla sin píxeles muertos. Rieles de Joy-Cons probados a 100% de retención. Batería al 99% de capacidad.');

INSERT INTO CERTIFICADOS_GS (ID_PRODUCTO, CODIGO_CERTIFICADO, HARDWARE_ORIGINAL_PCT, ESTADO_ESTETICO_PCT, RENDIMIENTO_TERMICO_PCT, PUNTOS_REVISADOS, MESES_GARANTIA, DETALLE_INSPECCION)
VALUES (3, '#GS-2203', 100, 94, 96, 34, 12, 'Arquitectura de ventilación silenciosa probada durante 4 horas en 4K. Sello original preservado.');

INSERT INTO CERTIFICADOS_GS (ID_PRODUCTO, CODIGO_CERTIFICADO, HARDWARE_ORIGINAL_PCT, ESTADO_ESTETICO_PCT, RENDIMIENTO_TERMICO_PCT, PUNTOS_REVISADOS, MESES_GARANTIA, DETALLE_INSPECCION)
VALUES (4, '#GS-2204', 100, 95, 95, 40, 18, 'Stress test CPU/GPU de 6 horas en sintéticos y juegos AAA. Pasta térmica con metal líquido limpia.');

INSERT INTO CERTIFICADOS_GS (ID_PRODUCTO, CODIGO_CERTIFICADO, HARDWARE_ORIGINAL_PCT, ESTADO_ESTETICO_PCT, RENDIMIENTO_TERMICO_PCT, PUNTOS_REVISADOS, MESES_GARANTIA, DETALLE_INSPECCION)
VALUES (5, '#GS-2205', 100, 99, 99, 42, 18, 'Unidad de exhibición de laboratorio impecable. Rendimiento térmico extremo con 0% throttling.');

INSERT INTO CERTIFICADOS_GS (ID_PRODUCTO, CODIGO_CERTIFICADO, HARDWARE_ORIGINAL_PCT, ESTADO_ESTETICO_PCT, RENDIMIENTO_TERMICO_PCT, PUNTOS_REVISADOS, MESES_GARANTIA, DETALLE_INSPECCION)
VALUES (6, '#GS-2206', 95, 92, 96, 38, 6, 'Recapacitado total con capacitores japoneses Nichicon. Carcasa original desinfectada y tratada UV.');

INSERT INTO CERTIFICADOS_GS (ID_PRODUCTO, CODIGO_CERTIFICADO, HARDWARE_ORIGINAL_PCT, ESTADO_ESTETICO_PCT, RENDIMIENTO_TERMICO_PCT, PUNTOS_REVISADOS, MESES_GARANTIA, DETALLE_INSPECCION)
VALUES (7, '#GS-2207', 90, 88, 94, 30, 6, 'Audio amplificado sin ruidos parásitos. Botones de goma cambiados por repuestos OEM.');

INSERT INTO CERTIFICADOS_GS (ID_PRODUCTO, CODIGO_CERTIFICADO, HARDWARE_ORIGINAL_PCT, ESTADO_ESTETICO_PCT, RENDIMIENTO_TERMICO_PCT, PUNTOS_REVISADOS, MESES_GARANTIA, DETALLE_INSPECCION)
VALUES (8, '#GS-2208', 100, 93, 97, 33, 6, 'Consola probada con cartuchos originales de alta demanda de corriente. Jack de audio frontal calibrado.');

-- 7. DETALLES ESPECÍFICOS DE LAPTOPS GAMER
INSERT INTO PRODUCTOS_DETALLE_LAPTOP (ID_PRODUCTO, PROCESADOR, GPU, RAM_GB, ALMACENAMIENTO_GB, SALUD_BATERIA_PCT, TEST_TERMICO_APROBADO)
VALUES (4, 'Intel Core i7-13650HX', 'NVIDIA GeForce RTX 4070 8GB', 16, 1000, 98, 'S');

INSERT INTO PRODUCTOS_DETALLE_LAPTOP (ID_PRODUCTO, PROCESADOR, GPU, RAM_GB, ALMACENAMIENTO_GB, SALUD_BATERIA_PCT, TEST_TERMICO_APROBADO)
VALUES (5, 'Intel Core i9-13980HX', 'NVIDIA GeForce RTX 4080 12GB', 32, 2000, 100, 'S');

-- 8. DETALLES ESPECÍFICOS DE RETRO RESTORATION
INSERT INTO PRODUCTOS_DETALLE_RETRO (ID_PRODUCTO, CONDICION_ESTETICA_10, INCLUYE_CAJA, INCLUYE_MANUAL, ESTADO_FUNCIONAL, RECAP_REALIZADO)
VALUES (6, 9, 'S', 'S', 'RESTAURO_TOTAL', 'S');

INSERT INTO PRODUCTOS_DETALLE_RETRO (ID_PRODUCTO, CONDICION_ESTETICA_10, INCLUYE_CAJA, INCLUYE_MANUAL, ESTADO_FUNCIONAL, RECAP_REALIZADO)
VALUES (7, 8, 'N', 'N', 'RESTAURO_TOTAL', 'S');

INSERT INTO PRODUCTOS_DETALLE_RETRO (ID_PRODUCTO, CONDICION_ESTETICA_10, INCLUYE_CAJA, INCLUYE_MANUAL, ESTADO_FUNCIONAL, RECAP_REALIZADO)
VALUES (8, 9, 'S', 'N', 'RESTAURO_TOTAL', 'S');

-- 9. INSERSIONES DE VENTAS INICIALES (EN EFECTIVO / TRANSFERENCIA)
INSERT INTO VENTAS (ID_CLIENTE, METODO_PAGO, TOTAL_VENTA, NOTAS_VENTA) 
VALUES (1, 'TARJETA', 849.98, 'Venta presencial en tienda con boleta emitida.');

INSERT INTO VENTAS (ID_CLIENTE, METODO_PAGO, TOTAL_VENTA, NOTAS_VENTA) 
VALUES (2, 'EFECTIVO', 189.99, 'Pago en efectivo directo al momento del recojo.');

INSERT INTO VENTAS (ID_CLIENTE, METODO_PAGO, TOTAL_VENTA, NOTAS_VENTA) 
VALUES (3, 'TRANSFERENCIA', 1499.99, 'Transferencia bancaria directa comprobada.');

INSERT INTO VENTAS_DETALLE (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (1, 1, 1, 499.99);
INSERT INTO VENTAS_DETALLE (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (1, 2, 1, 349.99);
INSERT INTO VENTAS_DETALLE (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (2, 6, 1, 189.99);
INSERT INTO VENTAS_DETALLE (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (3, 4, 1, 1499.99);

-- 10. CUPONES DE DESCUENTO
INSERT INTO CUPONES_DESCUENTO (CODIGO, PORCENTAJE_DESCUENTO, FECHA_EXPIRACION) 
VALUES ('GAMING10', 10.00, ADD_MONTHS(SYSDATE, 6));

INSERT INTO CUPONES_DESCUENTO (CODIGO, MONTO_DESCUENTO, FECHA_EXPIRACION) 
VALUES ('BIENVENIDA50', 50.00, ADD_MONTHS(SYSDATE, 3));

COMMIT;
