-- Gaming Solutions: migración incremental (ejecutar después de 01_schema.sql).
-- No elimina datos ni depende de que el esquema se instale desde cero.
DECLARE
  PROCEDURE agregar_columna(p_tabla VARCHAR2, p_columna VARCHAR2, p_definicion VARCHAR2) IS
    l_existe NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_existe FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = UPPER(p_tabla) AND COLUMN_NAME = UPPER(p_columna);
    IF l_existe = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_tabla || ' ADD (' || p_columna || ' ' || p_definicion || ')';
    END IF;
  END;
  PROCEDURE agregar_restriccion(p_nombre VARCHAR2, p_sql VARCHAR2) IS
    l_existe NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_existe FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = UPPER(p_nombre);
    IF l_existe = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
  PROCEDURE agregar_indice(p_nombre VARCHAR2, p_sql VARCHAR2) IS
    l_existe NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_existe FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_nombre);
    IF l_existe = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  agregar_columna('CLIENTES', 'NIT', 'VARCHAR2(30)');
  agregar_columna('CLIENTES', 'DPI', 'VARCHAR2(30)');
  agregar_columna('PROVEEDORES', 'NIT', 'VARCHAR2(30)');
  agregar_columna('PRODUCTOS', 'TIPO_PRODUCTO', 'VARCHAR2(20) DEFAULT ''NUEVO'' NOT NULL');
  agregar_columna('PRODUCTOS', 'IMAGEN_URL', 'VARCHAR2(500)');
  agregar_columna('PRODUCTOS', 'TIEMPO_GARANTIA_MESES', 'NUMBER(3) DEFAULT 12 NOT NULL');
  agregar_columna('PRODUCTOS', 'HW_INSPECCION_PCT', 'NUMBER(3)');
  agregar_columna('PRODUCTOS', 'ESTETICA_INSPECCION_PCT', 'NUMBER(3)');
  agregar_columna('PRODUCTOS', 'TERMICO_INSPECCION_PCT', 'NUMBER(3)');
  EXECUTE IMMEDIATE 'UPDATE PRODUCTOS SET TIPO_PRODUCTO = CASE WHEN TIPO_HARDWARE = ''RETRO'' THEN ''USADO'' ELSE ''NUEVO'' END WHERE TIPO_PRODUCTO IS NULL';
  EXECUTE IMMEDIATE 'UPDATE PRODUCTOS SET TIEMPO_GARANTIA_MESES = 12 WHERE TIEMPO_GARANTIA_MESES IS NULL';
  agregar_restriccion('CK_PRODUCTOS_TIPO_PRODUCTO', 'ALTER TABLE PRODUCTOS ADD CONSTRAINT CK_PRODUCTOS_TIPO_PRODUCTO CHECK (TIPO_PRODUCTO IN (''NUEVO'',''USADO'',''REACONDICIONADO''))');
  agregar_restriccion('CK_PRODUCTOS_GARANTIA', 'ALTER TABLE PRODUCTOS ADD CONSTRAINT CK_PRODUCTOS_GARANTIA CHECK (TIEMPO_GARANTIA_MESES BETWEEN 0 AND 120)');
  agregar_restriccion('UK_CLIENTES_NIT', 'ALTER TABLE CLIENTES ADD CONSTRAINT UK_CLIENTES_NIT UNIQUE (NIT)');
  agregar_restriccion('UK_CLIENTES_DPI', 'ALTER TABLE CLIENTES ADD CONSTRAINT UK_CLIENTES_DPI UNIQUE (DPI)');
  agregar_restriccion('UK_PROVEEDORES_NIT', 'ALTER TABLE PROVEEDORES ADD CONSTRAINT UK_PROVEEDORES_NIT UNIQUE (NIT)');
  agregar_indice('IX_PRODUCTOS_IMAGEN', 'CREATE INDEX IX_PRODUCTOS_IMAGEN ON PRODUCTOS(IMAGEN_URL)');
  COMMIT;
END;
/
